spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=task
spring.datasource.password=task
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id= ${GOOGLE-CLIENT-ID}
spring.security.oauth2.client.registration.google.client-secret= ${GOOGLE-CLIENT-SECRET}

# habilitando a interface e doc do swagger para a minha api
springdoc.swagger-ui.enable=true
springdoc.api-docs.enable=true

# proibindo de sobrescrever com resposta genericas, nao ira colocar status http de retorno padrao na api
springdoc.override-with-response-generic=false

# habilitando cores de log no console
spring.output.ansi.enabled=ALWAYS

# habilitando customizacao de log no console
logging.pattern.console= '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'

# gerando arquivo de log para monitoramento
# temos 5 niveis de log, esta em ordem habilitando um habilita os demais abaixo, fica a seu criterio criar um log para qualquer arquivo da aplicacao
# trace - ira mostrar tudo detalhado desde a inicializacao do projeto
# debug
# info - informacoes
# warn - algum aviso
# error - algum erro no sistema

logging.file.name=taskmanager.log
logging.file.level.root=warn

# configurando o actuator
# expondo a porta 9090 para o actuator
management.server.port=9090
# incluindo todos os endpoints web no actuator
management.endpoints.web.exposure.include= '*'