spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=task
spring.datasource.password=task
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id= ${GOOGLE-CLIENT-ID}
spring.security.oauth2.client.registration.google.client-secret= ${GOOGLE-CLIENT-SECRET}

# habilitando a interface e doc do swagger para a minha api
springdoc.swagger-ui.enable=true
springdoc.api-docs.enable=true

# proibindo de sobrescrever com resposta genericas, nao ira colocar status http de retorno padrao na api
springdoc.override-with-response-generic=false

# gerando arquivo de log para monitoramento
logging.file.name=taskmanager.log